// Seed D1 from lib/routes.js by writing a single SQL file and shelling out
// to `wrangler d1 execute`. We deliberately avoid Node-side SQLite drivers —
// wrangler is the source of truth for both local and remote D1.
//
// Usage:
//   node scripts/seed-d1.mjs --local    (writes to .wrangler/state/v3/d1)
//   node scripts/seed-d1.mjs --remote   (writes to the live D1 database)
//
// On --remote, every existing row in routes/stops is wiped before seeding, so
// the script is idempotent. Ratings and feedback are never touched.

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const SQL_OUT = path.join(ROOT, "scripts", ".seed.generated.sql");

const target = process.argv.includes("--remote") ? "--remote" : "--local";

// Routes live in data/routes.seed.json so we don't need to import lib/routes.js
// at seed time (avoids the ESM-vs-CJS parser warning, and keeps the seed step
// independent of front-end code).
const ROUTES = JSON.parse(
  fs.readFileSync(path.join(ROOT, "data", "routes.seed.json"), "utf8"),
);

function deriveIntensity(distanceKm) {
  if (distanceKm < 3) return "轻松散步";
  if (distanceKm <= 6) return "中等步行";
  return "长距离暴走";
}

// Walking paths now live in D1 (routes.walking_path column). The seed leaves
// them NULL — they get populated by a separate one-shot script that calls
// AMap and writes the path back into D1.
const WALKING_PATHS = {};

function sqlString(v) {
  if (v == null) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}
function sqlInt(v) {
  if (v == null) return "NULL";
  return String(Math.round(Number(v)));
}
function sqlReal(v) {
  if (v == null) return "NULL";
  return String(Number(v));
}
function sqlJson(v) {
  if (v == null) return "'[]'";
  return sqlString(JSON.stringify(v));
}

const lines = [];
// D1's `wrangler d1 execute --file` already wraps the file in an atomic
// transaction, so we must NOT emit our own BEGIN/COMMIT — D1 rejects them.
lines.push("-- Generated by scripts/seed-d1.mjs. Do not commit.");
lines.push("DELETE FROM stops;");
lines.push("DELETE FROM routes;");

for (const r of ROUTES) {
  const intensity = deriveIntensity(r.distanceKm);
  const walkingPath = WALKING_PATHS[r.id] || null;
  lines.push(
    `INSERT INTO routes (id, name, name_en, hook, hook_en, theme, atmosphere, intensity, distance_km, duration_min, district, tags, cover_color, walking_path, published_at, is_published) VALUES (` +
      [
        sqlString(r.id),
        sqlString(r.name),
        sqlString(r.name_en),
        sqlString(r.hook),
        sqlString(r.hook_en),
        sqlString(r.theme),
        sqlString(r.atmosphere),
        sqlString(intensity),
        sqlReal(r.distanceKm),
        sqlInt(r.durationMin),
        sqlString(r.district),
        sqlJson(r.tags || []),
        sqlString(r.coverColor),
        walkingPath ? sqlString(JSON.stringify(walkingPath)) : "NULL",
        sqlString(r.publishedAt),
        "1",
      ].join(", ") +
      ");",
  );
  (r.stops || []).forEach((s, i) => {
    lines.push(
      `INSERT INTO stops (route_id, ord, name, name_en, story, story_en, lat, lng, photos) VALUES (` +
        [
          sqlString(r.id),
          String(i),
          sqlString(s.name),
          sqlString(s.name_en),
          sqlString(s.story),
          sqlString(s.story_en),
          sqlReal(s.coords?.[0]),
          sqlReal(s.coords?.[1]),
          sqlJson(s.photos || []),
        ].join(", ") +
        ");",
    );
  });
}

// (no COMMIT — see note at the top of this file)

fs.writeFileSync(SQL_OUT, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${lines.length} SQL statements → ${path.relative(ROOT, SQL_OUT)}`);

const result = spawnSync(
  "npx",
  [
    "wrangler",
    "d1",
    "execute",
    "nongtangli",
    target,
    `--file=${SQL_OUT}`,
  ],
  { stdio: "inherit", cwd: ROOT },
);

if (result.status !== 0) {
  console.error(`wrangler exited with code ${result.status}`);
  process.exit(result.status ?? 1);
}

console.log(`Seeded ${ROUTES.length} routes into D1 (${target}).`);
